package com.hypersoft.baseproject.core.firebase

object EventsProvider {
    const val ENTRANCE_SCREEN = "ENTRANCE_SCREEN"

    const val LANGUAGE_SCREEN = "LANGUAGE_SCREEN"
    const val LANGUAGE_CONTINUE_BUTTON = "LANGUAGE_CONTINUE_BUTTON"

    const val ON_BOARDING_SCREEN = "ON_BOARDING_SCREEN"
    const val ON_BOARDING_SCREEN_ONE = "ON_BOARDING_SCREEN_ONE"
    const val ON_BOARDING_SCREEN_TWO = "ON_BOARDING_SCREEN_TWO"
    const val ON_BOARDING_SCREEN_THREE = "ON_BOARDING_SCREEN_THREE"
    const val ON_BOARDING_CONTINUE_BUTTON = "ON_BOARDING_CONTINUE_BUTTON"

    const val MENU_SCREEN = "MENU_SCREEN"
    const val MENU_CONTINUE_BUTTON = "MENU_CONTINUE_BUTTON"

    const val DASHBOARD_SCREEN = "DASHBOARD_SCREEN"

    const val IN_APP_LANGUAGE_SCREEN = "IN_APP_LANGUAGE_SCREEN"
    const val IN_APP_LANGUAGE_CONTINUE_BUTTON = "IN_APP_LANGUAGE_CONTINUE_BUTTON"

    const val EXIT_SCREEN = "EXIT_SCREEN"
}